# Generated by Django 5.0 on 2023-12-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0003_rename_description_fruit_description2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruit',
            old_name='description2',
            new_name='description',
        ),
        migrations.AddField(
            model_name='fruit',
            name='image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
